// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: pb/v1/vending_machine.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VendingMachineService_GetVendingMachineByID_FullMethodName    = "/api.v1.VendingMachineService/GetVendingMachineByID"
	VendingMachineService_GetSales_FullMethodName                 = "/api.v1.VendingMachineService/GetSales"
	VendingMachineService_GetActions_FullMethodName               = "/api.v1.VendingMachineService/GetActions"
	VendingMachineService_GetVMStates_FullMethodName              = "/api.v1.VendingMachineService/GetVMStates"
	VendingMachineService_GetEvents_FullMethodName                = "/api.v1.VendingMachineService/GetEvents"
	VendingMachineService_SendCommand_FullMethodName              = "/api.v1.VendingMachineService/SendCommand"
	VendingMachineService_GetVendingMachineRemains_FullMethodName = "/api.v1.VendingMachineService/GetVendingMachineRemains"
)

// VendingMachineServiceClient is the client API for VendingMachineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VendingMachineServiceClient interface {
	GetVendingMachineByID(ctx context.Context, in *GetVendingMachineByIDRequest, opts ...grpc.CallOption) (*GetVendingMachineByIDResponse, error)
	GetSales(ctx context.Context, in *GetSalesRequest, opts ...grpc.CallOption) (*GetSalesResponse, error)
	GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error)
	GetVMStates(ctx context.Context, in *GetVMStatesRequest, opts ...grpc.CallOption) (*GetVMStatesResponse, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error)
	GetVendingMachineRemains(ctx context.Context, in *GetVendingMachineRemainsRequest, opts ...grpc.CallOption) (*GetVendingMachineRemainsResponse, error)
}

type vendingMachineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVendingMachineServiceClient(cc grpc.ClientConnInterface) VendingMachineServiceClient {
	return &vendingMachineServiceClient{cc}
}

func (c *vendingMachineServiceClient) GetVendingMachineByID(ctx context.Context, in *GetVendingMachineByIDRequest, opts ...grpc.CallOption) (*GetVendingMachineByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVendingMachineByIDResponse)
	err := c.cc.Invoke(ctx, VendingMachineService_GetVendingMachineByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendingMachineServiceClient) GetSales(ctx context.Context, in *GetSalesRequest, opts ...grpc.CallOption) (*GetSalesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSalesResponse)
	err := c.cc.Invoke(ctx, VendingMachineService_GetSales_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendingMachineServiceClient) GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActionsResponse)
	err := c.cc.Invoke(ctx, VendingMachineService_GetActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendingMachineServiceClient) GetVMStates(ctx context.Context, in *GetVMStatesRequest, opts ...grpc.CallOption) (*GetVMStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMStatesResponse)
	err := c.cc.Invoke(ctx, VendingMachineService_GetVMStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendingMachineServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, VendingMachineService_GetEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendingMachineServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCommandResponse)
	err := c.cc.Invoke(ctx, VendingMachineService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendingMachineServiceClient) GetVendingMachineRemains(ctx context.Context, in *GetVendingMachineRemainsRequest, opts ...grpc.CallOption) (*GetVendingMachineRemainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVendingMachineRemainsResponse)
	err := c.cc.Invoke(ctx, VendingMachineService_GetVendingMachineRemains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VendingMachineServiceServer is the server API for VendingMachineService service.
// All implementations must embed UnimplementedVendingMachineServiceServer
// for forward compatibility.
type VendingMachineServiceServer interface {
	GetVendingMachineByID(context.Context, *GetVendingMachineByIDRequest) (*GetVendingMachineByIDResponse, error)
	GetSales(context.Context, *GetSalesRequest) (*GetSalesResponse, error)
	GetActions(context.Context, *GetActionsRequest) (*GetActionsResponse, error)
	GetVMStates(context.Context, *GetVMStatesRequest) (*GetVMStatesResponse, error)
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error)
	GetVendingMachineRemains(context.Context, *GetVendingMachineRemainsRequest) (*GetVendingMachineRemainsResponse, error)
	mustEmbedUnimplementedVendingMachineServiceServer()
}

// UnimplementedVendingMachineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVendingMachineServiceServer struct{}

func (UnimplementedVendingMachineServiceServer) GetVendingMachineByID(context.Context, *GetVendingMachineByIDRequest) (*GetVendingMachineByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVendingMachineByID not implemented")
}
func (UnimplementedVendingMachineServiceServer) GetSales(context.Context, *GetSalesRequest) (*GetSalesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSales not implemented")
}
func (UnimplementedVendingMachineServiceServer) GetActions(context.Context, *GetActionsRequest) (*GetActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActions not implemented")
}
func (UnimplementedVendingMachineServiceServer) GetVMStates(context.Context, *GetVMStatesRequest) (*GetVMStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMStates not implemented")
}
func (UnimplementedVendingMachineServiceServer) GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedVendingMachineServiceServer) SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedVendingMachineServiceServer) GetVendingMachineRemains(context.Context, *GetVendingMachineRemainsRequest) (*GetVendingMachineRemainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVendingMachineRemains not implemented")
}
func (UnimplementedVendingMachineServiceServer) mustEmbedUnimplementedVendingMachineServiceServer() {}
func (UnimplementedVendingMachineServiceServer) testEmbeddedByValue()                               {}

// UnsafeVendingMachineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VendingMachineServiceServer will
// result in compilation errors.
type UnsafeVendingMachineServiceServer interface {
	mustEmbedUnimplementedVendingMachineServiceServer()
}

func RegisterVendingMachineServiceServer(s grpc.ServiceRegistrar, srv VendingMachineServiceServer) {
	// If the following call panics, it indicates UnimplementedVendingMachineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VendingMachineService_ServiceDesc, srv)
}

func _VendingMachineService_GetVendingMachineByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendingMachineByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendingMachineServiceServer).GetVendingMachineByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendingMachineService_GetVendingMachineByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendingMachineServiceServer).GetVendingMachineByID(ctx, req.(*GetVendingMachineByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendingMachineService_GetSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendingMachineServiceServer).GetSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendingMachineService_GetSales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendingMachineServiceServer).GetSales(ctx, req.(*GetSalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendingMachineService_GetActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendingMachineServiceServer).GetActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendingMachineService_GetActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendingMachineServiceServer).GetActions(ctx, req.(*GetActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendingMachineService_GetVMStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendingMachineServiceServer).GetVMStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendingMachineService_GetVMStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendingMachineServiceServer).GetVMStates(ctx, req.(*GetVMStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendingMachineService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendingMachineServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendingMachineService_GetEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendingMachineServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendingMachineService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendingMachineServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendingMachineService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendingMachineServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VendingMachineService_GetVendingMachineRemains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVendingMachineRemainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendingMachineServiceServer).GetVendingMachineRemains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VendingMachineService_GetVendingMachineRemains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendingMachineServiceServer).GetVendingMachineRemains(ctx, req.(*GetVendingMachineRemainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VendingMachineService_ServiceDesc is the grpc.ServiceDesc for VendingMachineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VendingMachineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.VendingMachineService",
	HandlerType: (*VendingMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVendingMachineByID",
			Handler:    _VendingMachineService_GetVendingMachineByID_Handler,
		},
		{
			MethodName: "GetSales",
			Handler:    _VendingMachineService_GetSales_Handler,
		},
		{
			MethodName: "GetActions",
			Handler:    _VendingMachineService_GetActions_Handler,
		},
		{
			MethodName: "GetVMStates",
			Handler:    _VendingMachineService_GetVMStates_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _VendingMachineService_GetEvents_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _VendingMachineService_SendCommand_Handler,
		},
		{
			MethodName: "GetVendingMachineRemains",
			Handler:    _VendingMachineService_GetVendingMachineRemains_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/v1/vending_machine.proto",
}
