// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/v1/vending_machine.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VendingMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CompanyId     int32                  `protobuf:"varint,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendingMachine) Reset() {
	*x = VendingMachine{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendingMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendingMachine) ProtoMessage() {}

func (x *VendingMachine) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendingMachine.ProtoReflect.Descriptor instead.
func (*VendingMachine) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{0}
}

func (x *VendingMachine) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VendingMachine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VendingMachine) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

type GetVendingMachineByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVendingMachineByIDRequest) Reset() {
	*x = GetVendingMachineByIDRequest{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendingMachineByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendingMachineByIDRequest) ProtoMessage() {}

func (x *GetVendingMachineByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendingMachineByIDRequest.ProtoReflect.Descriptor instead.
func (*GetVendingMachineByIDRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{1}
}

func (x *GetVendingMachineByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVendingMachineByIDResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VendingMachine *VendingMachine        `protobuf:"bytes,1,opt,name=vending_machine,json=vendingMachine,proto3" json:"vending_machine,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVendingMachineByIDResponse) Reset() {
	*x = GetVendingMachineByIDResponse{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendingMachineByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendingMachineByIDResponse) ProtoMessage() {}

func (x *GetVendingMachineByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendingMachineByIDResponse.ProtoReflect.Descriptor instead.
func (*GetVendingMachineByIDResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{2}
}

func (x *GetVendingMachineByIDResponse) GetVendingMachine() *VendingMachine {
	if x != nil {
		return x.VendingMachine
	}
	return nil
}

type Sale struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendingMachineId int32                  `protobuf:"varint,2,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	GoodsId          int32                  `protobuf:"varint,3,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsName        string                 `protobuf:"bytes,4,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	Count            int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Sum              float64                `protobuf:"fixed64,6,opt,name=sum,proto3" json:"sum,omitempty"`
	DateTime         string                 `protobuf:"bytes,7,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	PaymentMethod    int32                  `protobuf:"varint,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Sale) Reset() {
	*x = Sale{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sale) ProtoMessage() {}

func (x *Sale) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sale.ProtoReflect.Descriptor instead.
func (*Sale) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{3}
}

func (x *Sale) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sale) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

func (x *Sale) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *Sale) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *Sale) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Sale) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Sale) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

func (x *Sale) GetPaymentMethod() int32 {
	if x != nil {
		return x.PaymentMethod
	}
	return 0
}

type GetSalesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromDate         string                 `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate           string                 `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	VendingMachineId int32                  `protobuf:"varint,3,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSalesRequest) Reset() {
	*x = GetSalesRequest{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesRequest) ProtoMessage() {}

func (x *GetSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesRequest.ProtoReflect.Descriptor instead.
func (*GetSalesRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{4}
}

func (x *GetSalesRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetSalesRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *GetSalesRequest) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

type GetSalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sales         []*Sale                `protobuf:"bytes,1,rep,name=sales,proto3" json:"sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesResponse) Reset() {
	*x = GetSalesResponse{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesResponse) ProtoMessage() {}

func (x *GetSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesResponse.ProtoReflect.Descriptor instead.
func (*GetSalesResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{5}
}

func (x *GetSalesResponse) GetSales() []*Sale {
	if x != nil {
		return x.Sales
	}
	return nil
}

type Action struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendingMachineId int32                  `protobuf:"varint,2,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	ActionType       int32                  `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	DateTime         string                 `protobuf:"bytes,4,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{6}
}

func (x *Action) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Action) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

func (x *Action) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *Action) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

type GetActionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromDate         string                 `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate           string                 `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	VendingMachineId int32                  `protobuf:"varint,3,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetActionsRequest) Reset() {
	*x = GetActionsRequest{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsRequest) ProtoMessage() {}

func (x *GetActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionsRequest.ProtoReflect.Descriptor instead.
func (*GetActionsRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{7}
}

func (x *GetActionsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetActionsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *GetActionsRequest) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

type GetActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionsResponse) Reset() {
	*x = GetActionsResponse{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsResponse) ProtoMessage() {}

func (x *GetActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionsResponse.ProtoReflect.Descriptor instead.
func (*GetActionsResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{8}
}

func (x *GetActionsResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type VMState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VendingMachineId int32                  `protobuf:"varint,1,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	MachineName      string                 `protobuf:"bytes,2,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`
	IsOnline         bool                   `protobuf:"varint,3,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	LastActivityTime string                 `protobuf:"bytes,4,opt,name=last_activity_time,json=lastActivityTime,proto3" json:"last_activity_time,omitempty"`
	PowerSupply      int32                  `protobuf:"varint,5,opt,name=power_supply,json=powerSupply,proto3" json:"power_supply,omitempty"`
	BillAcceptor     int32                  `protobuf:"varint,6,opt,name=bill_acceptor,json=billAcceptor,proto3" json:"bill_acceptor,omitempty"`
	CoinAcceptor     int32                  `protobuf:"varint,7,opt,name=coin_acceptor,json=coinAcceptor,proto3" json:"coin_acceptor,omitempty"`
	NonCashPayment   int32                  `protobuf:"varint,8,opt,name=non_cash_payment,json=nonCashPayment,proto3" json:"non_cash_payment,omitempty"`
	CashRegister     int32                  `protobuf:"varint,9,opt,name=cash_register,json=cashRegister,proto3" json:"cash_register,omitempty"`
	QrDisplay        int32                  `protobuf:"varint,10,opt,name=qr_display,json=qrDisplay,proto3" json:"qr_display,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VMState) Reset() {
	*x = VMState{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMState) ProtoMessage() {}

func (x *VMState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMState.ProtoReflect.Descriptor instead.
func (*VMState) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{9}
}

func (x *VMState) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

func (x *VMState) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *VMState) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *VMState) GetLastActivityTime() string {
	if x != nil {
		return x.LastActivityTime
	}
	return ""
}

func (x *VMState) GetPowerSupply() int32 {
	if x != nil {
		return x.PowerSupply
	}
	return 0
}

func (x *VMState) GetBillAcceptor() int32 {
	if x != nil {
		return x.BillAcceptor
	}
	return 0
}

func (x *VMState) GetCoinAcceptor() int32 {
	if x != nil {
		return x.CoinAcceptor
	}
	return 0
}

func (x *VMState) GetNonCashPayment() int32 {
	if x != nil {
		return x.NonCashPayment
	}
	return 0
}

func (x *VMState) GetCashRegister() int32 {
	if x != nil {
		return x.CashRegister
	}
	return 0
}

func (x *VMState) GetQrDisplay() int32 {
	if x != nil {
		return x.QrDisplay
	}
	return 0
}

type GetVMStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMStatesRequest) Reset() {
	*x = GetVMStatesRequest{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMStatesRequest) ProtoMessage() {}

func (x *GetVMStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMStatesRequest.ProtoReflect.Descriptor instead.
func (*GetVMStatesRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{10}
}

type GetVMStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmStates      []*VMState             `protobuf:"bytes,1,rep,name=vm_states,json=vmStates,proto3" json:"vm_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMStatesResponse) Reset() {
	*x = GetVMStatesResponse{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMStatesResponse) ProtoMessage() {}

func (x *GetVMStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMStatesResponse.ProtoReflect.Descriptor instead.
func (*GetVMStatesResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{11}
}

func (x *GetVMStatesResponse) GetVmStates() []*VMState {
	if x != nil {
		return x.VmStates
	}
	return nil
}

type Event struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendingMachineId int32                  `protobuf:"varint,2,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	EventCode        int32                  `protobuf:"varint,3,opt,name=event_code,json=eventCode,proto3" json:"event_code,omitempty"`
	DateTime         string                 `protobuf:"bytes,4,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{12}
}

func (x *Event) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

func (x *Event) GetEventCode() int32 {
	if x != nil {
		return x.EventCode
	}
	return 0
}

func (x *Event) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetEventsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromDate         string                 `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate           string                 `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	VendingMachineId int32                  `protobuf:"varint,3,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{13}
}

func (x *GetEventsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetEventsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *GetEventsRequest) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{14}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Command struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VendingMachineId int32                  `protobuf:"varint,1,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	CommandCode      int32                  `protobuf:"varint,2,opt,name=command_code,json=commandCode,proto3" json:"command_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{15}
}

func (x *Command) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

func (x *Command) GetCommandCode() int32 {
	if x != nil {
		return x.CommandCode
	}
	return 0
}

type SendCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{16}
}

func (x *SendCommandRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type SendCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	CommandId     int32                  `protobuf:"varint,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{17}
}

func (x *SendCommandResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *SendCommandResponse) GetCommandId() int32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

type VendingMachineRemains struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VendingMachineId int32                  `protobuf:"varint,1,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	GoodsId          int32                  `protobuf:"varint,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsName        string                 `protobuf:"bytes,3,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	Count            int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VendingMachineRemains) Reset() {
	*x = VendingMachineRemains{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendingMachineRemains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendingMachineRemains) ProtoMessage() {}

func (x *VendingMachineRemains) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendingMachineRemains.ProtoReflect.Descriptor instead.
func (*VendingMachineRemains) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{18}
}

func (x *VendingMachineRemains) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

func (x *VendingMachineRemains) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *VendingMachineRemains) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *VendingMachineRemains) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetVendingMachineRemainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVendingMachineRemainsRequest) Reset() {
	*x = GetVendingMachineRemainsRequest{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendingMachineRemainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendingMachineRemainsRequest) ProtoMessage() {}

func (x *GetVendingMachineRemainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendingMachineRemainsRequest.ProtoReflect.Descriptor instead.
func (*GetVendingMachineRemainsRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{19}
}

func (x *GetVendingMachineRemainsRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVendingMachineRemainsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Remains       []*VendingMachineRemains `protobuf:"bytes,1,rep,name=remains,proto3" json:"remains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVendingMachineRemainsResponse) Reset() {
	*x = GetVendingMachineRemainsResponse{}
	mi := &file_pb_v1_vending_machine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendingMachineRemainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendingMachineRemainsResponse) ProtoMessage() {}

func (x *GetVendingMachineRemainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_vending_machine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendingMachineRemainsResponse.ProtoReflect.Descriptor instead.
func (*GetVendingMachineRemainsResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_vending_machine_proto_rawDescGZIP(), []int{20}
}

func (x *GetVendingMachineRemainsResponse) GetRemains() []*VendingMachineRemains {
	if x != nil {
		return x.Remains
	}
	return nil
}

var File_pb_v1_vending_machine_proto protoreflect.FileDescriptor

const file_pb_v1_vending_machine_proto_rawDesc = "" +
	"\n" +
	"\x1bpb/v1/vending_machine.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\"S\n" +
	"\x0eVendingMachine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\x05R\tcompanyId\".\n" +
	"\x1cGetVendingMachineByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"`\n" +
	"\x1dGetVendingMachineByIDResponse\x12?\n" +
	"\x0fvending_machine\x18\x01 \x01(\v2\x16.api.v1.VendingMachineR\x0evendingMachine\"\xea\x01\n" +
	"\x04Sale\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x12vending_machine_id\x18\x02 \x01(\x05R\x10vendingMachineId\x12\x19\n" +
	"\bgoods_id\x18\x03 \x01(\x05R\agoodsId\x12\x1d\n" +
	"\n" +
	"goods_name\x18\x04 \x01(\tR\tgoodsName\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12\x10\n" +
	"\x03sum\x18\x06 \x01(\x01R\x03sum\x12\x1b\n" +
	"\tdate_time\x18\a \x01(\tR\bdateTime\x12%\n" +
	"\x0epayment_method\x18\b \x01(\x05R\rpaymentMethod\"u\n" +
	"\x0fGetSalesRequest\x12\x1b\n" +
	"\tfrom_date\x18\x01 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x02 \x01(\tR\x06toDate\x12,\n" +
	"\x12vending_machine_id\x18\x03 \x01(\x05R\x10vendingMachineId\"6\n" +
	"\x10GetSalesResponse\x12\"\n" +
	"\x05sales\x18\x01 \x03(\v2\f.api.v1.SaleR\x05sales\"\x84\x01\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x12vending_machine_id\x18\x02 \x01(\x05R\x10vendingMachineId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\x05R\n" +
	"actionType\x12\x1b\n" +
	"\tdate_time\x18\x04 \x01(\tR\bdateTime\"w\n" +
	"\x11GetActionsRequest\x12\x1b\n" +
	"\tfrom_date\x18\x01 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x02 \x01(\tR\x06toDate\x12,\n" +
	"\x12vending_machine_id\x18\x03 \x01(\x05R\x10vendingMachineId\">\n" +
	"\x12GetActionsResponse\x12(\n" +
	"\aactions\x18\x01 \x03(\v2\x0e.api.v1.ActionR\aactions\"\x80\x03\n" +
	"\aVMState\x12,\n" +
	"\x12vending_machine_id\x18\x01 \x01(\x05R\x10vendingMachineId\x12!\n" +
	"\fmachine_name\x18\x02 \x01(\tR\vmachineName\x12\x1b\n" +
	"\tis_online\x18\x03 \x01(\bR\bisOnline\x12,\n" +
	"\x12last_activity_time\x18\x04 \x01(\tR\x10lastActivityTime\x12!\n" +
	"\fpower_supply\x18\x05 \x01(\x05R\vpowerSupply\x12#\n" +
	"\rbill_acceptor\x18\x06 \x01(\x05R\fbillAcceptor\x12#\n" +
	"\rcoin_acceptor\x18\a \x01(\x05R\fcoinAcceptor\x12(\n" +
	"\x10non_cash_payment\x18\b \x01(\x05R\x0enonCashPayment\x12#\n" +
	"\rcash_register\x18\t \x01(\x05R\fcashRegister\x12\x1d\n" +
	"\n" +
	"qr_display\x18\n" +
	" \x01(\x05R\tqrDisplay\"\x14\n" +
	"\x12GetVMStatesRequest\"C\n" +
	"\x13GetVMStatesResponse\x12,\n" +
	"\tvm_states\x18\x01 \x03(\v2\x0f.api.v1.VMStateR\bvmStates\"\xa3\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x12vending_machine_id\x18\x02 \x01(\x05R\x10vendingMachineId\x12\x1d\n" +
	"\n" +
	"event_code\x18\x03 \x01(\x05R\teventCode\x12\x1b\n" +
	"\tdate_time\x18\x04 \x01(\tR\bdateTime\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"v\n" +
	"\x10GetEventsRequest\x12\x1b\n" +
	"\tfrom_date\x18\x01 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x02 \x01(\tR\x06toDate\x12,\n" +
	"\x12vending_machine_id\x18\x03 \x01(\x05R\x10vendingMachineId\":\n" +
	"\x11GetEventsResponse\x12%\n" +
	"\x06events\x18\x01 \x03(\v2\r.api.v1.EventR\x06events\"Z\n" +
	"\aCommand\x12,\n" +
	"\x12vending_machine_id\x18\x01 \x01(\x05R\x10vendingMachineId\x12!\n" +
	"\fcommand_code\x18\x02 \x01(\x05R\vcommandCode\"?\n" +
	"\x12SendCommandRequest\x12)\n" +
	"\acommand\x18\x01 \x01(\v2\x0f.api.v1.CommandR\acommand\"U\n" +
	"\x13SendCommandResponse\x12\x1f\n" +
	"\vresult_code\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\x05R\tcommandId\"\x95\x01\n" +
	"\x15VendingMachineRemains\x12,\n" +
	"\x12vending_machine_id\x18\x01 \x01(\x05R\x10vendingMachineId\x12\x19\n" +
	"\bgoods_id\x18\x02 \x01(\x05R\agoodsId\x12\x1d\n" +
	"\n" +
	"goods_name\x18\x03 \x01(\tR\tgoodsName\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"1\n" +
	"\x1fGetVendingMachineRemainsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"[\n" +
	" GetVendingMachineRemainsResponse\x127\n" +
	"\aremains\x18\x01 \x03(\v2\x1d.api.v1.VendingMachineRemainsR\aremains2\x9a\x06\n" +
	"\x15VendingMachineService\x12\x8b\x01\n" +
	"\x15GetVendingMachineByID\x12$.api.v1.GetVendingMachineByIDRequest\x1a%.api.v1.GetVendingMachineByIDResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/vending-machines/{id}\x12T\n" +
	"\bGetSales\x12\x17.api.v1.GetSalesRequest\x1a\x18.api.v1.GetSalesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/sales\x12\\\n" +
	"\n" +
	"GetActions\x12\x19.api.v1.GetActionsRequest\x1a\x1a.api.v1.GetActionsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/actions\x12a\n" +
	"\vGetVMStates\x12\x1a.api.v1.GetVMStatesRequest\x1a\x1b.api.v1.GetVMStatesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/vm-states\x12X\n" +
	"\tGetEvents\x12\x18.api.v1.GetEventsRequest\x1a\x19.api.v1.GetEventsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/events\x12c\n" +
	"\vSendCommand\x12\x1a.api.v1.SendCommandRequest\x1a\x1b.api.v1.SendCommandResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/commands\x12\x9c\x01\n" +
	"\x18GetVendingMachineRemains\x12'.api.v1.GetVendingMachineRemainsRequest\x1a(.api.v1.GetVendingMachineRemainsResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/vending-machines/{id}/remainsB&Z$github.com/St1cky1/kit_vend/pb/v1;v1b\x06proto3"

var (
	file_pb_v1_vending_machine_proto_rawDescOnce sync.Once
	file_pb_v1_vending_machine_proto_rawDescData []byte
)

func file_pb_v1_vending_machine_proto_rawDescGZIP() []byte {
	file_pb_v1_vending_machine_proto_rawDescOnce.Do(func() {
		file_pb_v1_vending_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_vending_machine_proto_rawDesc), len(file_pb_v1_vending_machine_proto_rawDesc)))
	})
	return file_pb_v1_vending_machine_proto_rawDescData
}

var file_pb_v1_vending_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pb_v1_vending_machine_proto_goTypes = []any{
	(*VendingMachine)(nil),                   // 0: api.v1.VendingMachine
	(*GetVendingMachineByIDRequest)(nil),     // 1: api.v1.GetVendingMachineByIDRequest
	(*GetVendingMachineByIDResponse)(nil),    // 2: api.v1.GetVendingMachineByIDResponse
	(*Sale)(nil),                             // 3: api.v1.Sale
	(*GetSalesRequest)(nil),                  // 4: api.v1.GetSalesRequest
	(*GetSalesResponse)(nil),                 // 5: api.v1.GetSalesResponse
	(*Action)(nil),                           // 6: api.v1.Action
	(*GetActionsRequest)(nil),                // 7: api.v1.GetActionsRequest
	(*GetActionsResponse)(nil),               // 8: api.v1.GetActionsResponse
	(*VMState)(nil),                          // 9: api.v1.VMState
	(*GetVMStatesRequest)(nil),               // 10: api.v1.GetVMStatesRequest
	(*GetVMStatesResponse)(nil),              // 11: api.v1.GetVMStatesResponse
	(*Event)(nil),                            // 12: api.v1.Event
	(*GetEventsRequest)(nil),                 // 13: api.v1.GetEventsRequest
	(*GetEventsResponse)(nil),                // 14: api.v1.GetEventsResponse
	(*Command)(nil),                          // 15: api.v1.Command
	(*SendCommandRequest)(nil),               // 16: api.v1.SendCommandRequest
	(*SendCommandResponse)(nil),              // 17: api.v1.SendCommandResponse
	(*VendingMachineRemains)(nil),            // 18: api.v1.VendingMachineRemains
	(*GetVendingMachineRemainsRequest)(nil),  // 19: api.v1.GetVendingMachineRemainsRequest
	(*GetVendingMachineRemainsResponse)(nil), // 20: api.v1.GetVendingMachineRemainsResponse
}
var file_pb_v1_vending_machine_proto_depIdxs = []int32{
	0,  // 0: api.v1.GetVendingMachineByIDResponse.vending_machine:type_name -> api.v1.VendingMachine
	3,  // 1: api.v1.GetSalesResponse.sales:type_name -> api.v1.Sale
	6,  // 2: api.v1.GetActionsResponse.actions:type_name -> api.v1.Action
	9,  // 3: api.v1.GetVMStatesResponse.vm_states:type_name -> api.v1.VMState
	12, // 4: api.v1.GetEventsResponse.events:type_name -> api.v1.Event
	15, // 5: api.v1.SendCommandRequest.command:type_name -> api.v1.Command
	18, // 6: api.v1.GetVendingMachineRemainsResponse.remains:type_name -> api.v1.VendingMachineRemains
	1,  // 7: api.v1.VendingMachineService.GetVendingMachineByID:input_type -> api.v1.GetVendingMachineByIDRequest
	4,  // 8: api.v1.VendingMachineService.GetSales:input_type -> api.v1.GetSalesRequest
	7,  // 9: api.v1.VendingMachineService.GetActions:input_type -> api.v1.GetActionsRequest
	10, // 10: api.v1.VendingMachineService.GetVMStates:input_type -> api.v1.GetVMStatesRequest
	13, // 11: api.v1.VendingMachineService.GetEvents:input_type -> api.v1.GetEventsRequest
	16, // 12: api.v1.VendingMachineService.SendCommand:input_type -> api.v1.SendCommandRequest
	19, // 13: api.v1.VendingMachineService.GetVendingMachineRemains:input_type -> api.v1.GetVendingMachineRemainsRequest
	2,  // 14: api.v1.VendingMachineService.GetVendingMachineByID:output_type -> api.v1.GetVendingMachineByIDResponse
	5,  // 15: api.v1.VendingMachineService.GetSales:output_type -> api.v1.GetSalesResponse
	8,  // 16: api.v1.VendingMachineService.GetActions:output_type -> api.v1.GetActionsResponse
	11, // 17: api.v1.VendingMachineService.GetVMStates:output_type -> api.v1.GetVMStatesResponse
	14, // 18: api.v1.VendingMachineService.GetEvents:output_type -> api.v1.GetEventsResponse
	17, // 19: api.v1.VendingMachineService.SendCommand:output_type -> api.v1.SendCommandResponse
	20, // 20: api.v1.VendingMachineService.GetVendingMachineRemains:output_type -> api.v1.GetVendingMachineRemainsResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_v1_vending_machine_proto_init() }
func file_pb_v1_vending_machine_proto_init() {
	if File_pb_v1_vending_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_vending_machine_proto_rawDesc), len(file_pb_v1_vending_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_v1_vending_machine_proto_goTypes,
		DependencyIndexes: file_pb_v1_vending_machine_proto_depIdxs,
		MessageInfos:      file_pb_v1_vending_machine_proto_msgTypes,
	}.Build()
	File_pb_v1_vending_machine_proto = out.File
	file_pb_v1_vending_machine_proto_goTypes = nil
	file_pb_v1_vending_machine_proto_depIdxs = nil
}
