// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/v1/courier.proto

package pb1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cell struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VendingMachineId int32                  `protobuf:"varint,2,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // free | occupied | blocked
	GoodsId          *int32                 `protobuf:"varint,4,opt,name=goods_id,json=goodsId,proto3,oneof" json:"goods_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_pb_v1_courier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_courier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_pb_v1_courier_proto_rawDescGZIP(), []int{0}
}

func (x *Cell) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cell) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

func (x *Cell) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Cell) GetGoodsId() int32 {
	if x != nil && x.GoodsId != nil {
		return *x.GoodsId
	}
	return 0
}

type GetCellsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VendingMachineId int32                  `protobuf:"varint,1,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCellsRequest) Reset() {
	*x = GetCellsRequest{}
	mi := &file_pb_v1_courier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellsRequest) ProtoMessage() {}

func (x *GetCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_courier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellsRequest.ProtoReflect.Descriptor instead.
func (*GetCellsRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_courier_proto_rawDescGZIP(), []int{1}
}

func (x *GetCellsRequest) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

type GetCellsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*Cell                `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellsResponse) Reset() {
	*x = GetCellsResponse{}
	mi := &file_pb_v1_courier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellsResponse) ProtoMessage() {}

func (x *GetCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_courier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellsResponse.ProtoReflect.Descriptor instead.
func (*GetCellsResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_courier_proto_rawDescGZIP(), []int{2}
}

func (x *GetCellsResponse) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type StartLoadSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VendingMachineId int32                  `protobuf:"varint,1,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	CourierId        int32                  `protobuf:"varint,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartLoadSessionRequest) Reset() {
	*x = StartLoadSessionRequest{}
	mi := &file_pb_v1_courier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoadSessionRequest) ProtoMessage() {}

func (x *StartLoadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_courier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoadSessionRequest.ProtoReflect.Descriptor instead.
func (*StartLoadSessionRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_courier_proto_rawDescGZIP(), []int{3}
}

func (x *StartLoadSessionRequest) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

func (x *StartLoadSessionRequest) GetCourierId() int32 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

type LoadSession struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VendingMachineId int32                  `protobuf:"varint,2,opt,name=vending_machine_id,json=vendingMachineId,proto3" json:"vending_machine_id,omitempty"`
	CourierId        int32                  `protobuf:"varint,3,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // active | completed | cancelled
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoadSession) Reset() {
	*x = LoadSession{}
	mi := &file_pb_v1_courier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSession) ProtoMessage() {}

func (x *LoadSession) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_courier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSession.ProtoReflect.Descriptor instead.
func (*LoadSession) Descriptor() ([]byte, []int) {
	return file_pb_v1_courier_proto_rawDescGZIP(), []int{4}
}

func (x *LoadSession) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadSession) GetVendingMachineId() int32 {
	if x != nil {
		return x.VendingMachineId
	}
	return 0
}

func (x *LoadSession) GetCourierId() int32 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

func (x *LoadSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoadSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *LoadSession) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type LoadCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	GoodsId       int32                  `protobuf:"varint,3,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCellRequest) Reset() {
	*x = LoadCellRequest{}
	mi := &file_pb_v1_courier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCellRequest) ProtoMessage() {}

func (x *LoadCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_courier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCellRequest.ProtoReflect.Descriptor instead.
func (*LoadCellRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_courier_proto_rawDescGZIP(), []int{5}
}

func (x *LoadCellRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *LoadCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *LoadCellRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type CompleteLoadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteLoadSessionRequest) Reset() {
	*x = CompleteLoadSessionRequest{}
	mi := &file_pb_v1_courier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteLoadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteLoadSessionRequest) ProtoMessage() {}

func (x *CompleteLoadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_courier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteLoadSessionRequest.ProtoReflect.Descriptor instead.
func (*CompleteLoadSessionRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_courier_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteLoadSessionRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

var File_pb_v1_courier_proto protoreflect.FileDescriptor

const file_pb_v1_courier_proto_rawDesc = "" +
	"\n" +
	"\x13pb/v1/courier.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n" +
	"\x04Cell\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12vending_machine_id\x18\x02 \x01(\x05R\x10vendingMachineId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1e\n" +
	"\bgoods_id\x18\x04 \x01(\x05H\x00R\agoodsId\x88\x01\x01B\v\n" +
	"\t_goods_id\"?\n" +
	"\x0fGetCellsRequest\x12,\n" +
	"\x12vending_machine_id\x18\x01 \x01(\x05R\x10vendingMachineId\"6\n" +
	"\x10GetCellsResponse\x12\"\n" +
	"\x05cells\x18\x01 \x03(\v2\f.api.v1.CellR\x05cells\"f\n" +
	"\x17StartLoadSessionRequest\x12,\n" +
	"\x12vending_machine_id\x18\x01 \x01(\x05R\x10vendingMachineId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x02 \x01(\x05R\tcourierId\"\x92\x02\n" +
	"\vLoadSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x12vending_machine_id\x18\x02 \x01(\x05R\x10vendingMachineId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x03 \x01(\x05R\tcourierId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12B\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcompletedAt\x88\x01\x01B\x0f\n" +
	"\r_completed_at\"d\n" +
	"\x0fLoadCellRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x05R\tsessionId\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\x12\x19\n" +
	"\bgoods_id\x18\x03 \x01(\x05R\agoodsId\";\n" +
	"\x1aCompleteLoadSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x05R\tsessionId2\x97\x04\n" +
	"\x0eCourierService\x12\x82\x01\n" +
	"\bGetCells\x12\x17.api.v1.GetCellsRequest\x1a\x18.api.v1.GetCellsResponse\"C\x82\xd3\xe4\x93\x02=\x12;/api/v1/courier/vending-machines/{vending_machine_id}/cells\x12r\n" +
	"\x10StartLoadSession\x12\x1f.api.v1.StartLoadSessionRequest\x1a\x13.api.v1.LoadSession\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/courier/load-sessions\x12x\n" +
	"\bLoadCell\x12\x17.api.v1.LoadCellRequest\x1a\x16.google.protobuf.Empty\";\x82\xd3\xe4\x93\x025:\x01*\"0/api/v1/courier/load-sessions/{session_id}/cells\x12\x91\x01\n" +
	"\x13CompleteLoadSession\x12\".api.v1.CompleteLoadSessionRequest\x1a\x16.google.protobuf.Empty\">\x82\xd3\xe4\x93\x028:\x01*\"3/api/v1/courier/load-sessions/{session_id}/completeB)Z'github.com/St1cky1/kit_vend/pkg/pb1;pb1b\x06proto3"

var (
	file_pb_v1_courier_proto_rawDescOnce sync.Once
	file_pb_v1_courier_proto_rawDescData []byte
)

func file_pb_v1_courier_proto_rawDescGZIP() []byte {
	file_pb_v1_courier_proto_rawDescOnce.Do(func() {
		file_pb_v1_courier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_courier_proto_rawDesc), len(file_pb_v1_courier_proto_rawDesc)))
	})
	return file_pb_v1_courier_proto_rawDescData
}

var file_pb_v1_courier_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_v1_courier_proto_goTypes = []any{
	(*Cell)(nil),                       // 0: api.v1.Cell
	(*GetCellsRequest)(nil),            // 1: api.v1.GetCellsRequest
	(*GetCellsResponse)(nil),           // 2: api.v1.GetCellsResponse
	(*StartLoadSessionRequest)(nil),    // 3: api.v1.StartLoadSessionRequest
	(*LoadSession)(nil),                // 4: api.v1.LoadSession
	(*LoadCellRequest)(nil),            // 5: api.v1.LoadCellRequest
	(*CompleteLoadSessionRequest)(nil), // 6: api.v1.CompleteLoadSessionRequest
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 8: google.protobuf.Empty
}
var file_pb_v1_courier_proto_depIdxs = []int32{
	0, // 0: api.v1.GetCellsResponse.cells:type_name -> api.v1.Cell
	7, // 1: api.v1.LoadSession.started_at:type_name -> google.protobuf.Timestamp
	7, // 2: api.v1.LoadSession.completed_at:type_name -> google.protobuf.Timestamp
	1, // 3: api.v1.CourierService.GetCells:input_type -> api.v1.GetCellsRequest
	3, // 4: api.v1.CourierService.StartLoadSession:input_type -> api.v1.StartLoadSessionRequest
	5, // 5: api.v1.CourierService.LoadCell:input_type -> api.v1.LoadCellRequest
	6, // 6: api.v1.CourierService.CompleteLoadSession:input_type -> api.v1.CompleteLoadSessionRequest
	2, // 7: api.v1.CourierService.GetCells:output_type -> api.v1.GetCellsResponse
	4, // 8: api.v1.CourierService.StartLoadSession:output_type -> api.v1.LoadSession
	8, // 9: api.v1.CourierService.LoadCell:output_type -> google.protobuf.Empty
	8, // 10: api.v1.CourierService.CompleteLoadSession:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_v1_courier_proto_init() }
func file_pb_v1_courier_proto_init() {
	if File_pb_v1_courier_proto != nil {
		return
	}
	file_pb_v1_courier_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_v1_courier_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_courier_proto_rawDesc), len(file_pb_v1_courier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_v1_courier_proto_goTypes,
		DependencyIndexes: file_pb_v1_courier_proto_depIdxs,
		MessageInfos:      file_pb_v1_courier_proto_msgTypes,
	}.Build()
	File_pb_v1_courier_proto = out.File
	file_pb_v1_courier_proto_goTypes = nil
	file_pb_v1_courier_proto_depIdxs = nil
}
