// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: pb/v1/courier.proto

package pb1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CourierService_GetCells_FullMethodName            = "/api.v1.CourierService/GetCells"
	CourierService_StartLoadSession_FullMethodName    = "/api.v1.CourierService/StartLoadSession"
	CourierService_LoadCell_FullMethodName            = "/api.v1.CourierService/LoadCell"
	CourierService_CompleteLoadSession_FullMethodName = "/api.v1.CourierService/CompleteLoadSession"
)

// CourierServiceClient is the client API for CourierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CourierService предоставляет методы для работы курьера с торговыми автоматами
type CourierServiceClient interface {
	// GetCells получает список ячеек автомата
	GetCells(ctx context.Context, in *GetCellsRequest, opts ...grpc.CallOption) (*GetCellsResponse, error)
	// StartLoadSession начинает сессию загрузки товара
	StartLoadSession(ctx context.Context, in *StartLoadSessionRequest, opts ...grpc.CallOption) (*LoadSession, error)
	// LoadCell загружает товар в конкретную ячейку
	LoadCell(ctx context.Context, in *LoadCellRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CompleteLoadSession завершает сессию загрузки
	CompleteLoadSession(ctx context.Context, in *CompleteLoadSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type courierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCourierServiceClient(cc grpc.ClientConnInterface) CourierServiceClient {
	return &courierServiceClient{cc}
}

func (c *courierServiceClient) GetCells(ctx context.Context, in *GetCellsRequest, opts ...grpc.CallOption) (*GetCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCellsResponse)
	err := c.cc.Invoke(ctx, CourierService_GetCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierServiceClient) StartLoadSession(ctx context.Context, in *StartLoadSessionRequest, opts ...grpc.CallOption) (*LoadSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadSession)
	err := c.cc.Invoke(ctx, CourierService_StartLoadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierServiceClient) LoadCell(ctx context.Context, in *LoadCellRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CourierService_LoadCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierServiceClient) CompleteLoadSession(ctx context.Context, in *CompleteLoadSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CourierService_CompleteLoadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourierServiceServer is the server API for CourierService service.
// All implementations must embed UnimplementedCourierServiceServer
// for forward compatibility.
//
// CourierService предоставляет методы для работы курьера с торговыми автоматами
type CourierServiceServer interface {
	// GetCells получает список ячеек автомата
	GetCells(context.Context, *GetCellsRequest) (*GetCellsResponse, error)
	// StartLoadSession начинает сессию загрузки товара
	StartLoadSession(context.Context, *StartLoadSessionRequest) (*LoadSession, error)
	// LoadCell загружает товар в конкретную ячейку
	LoadCell(context.Context, *LoadCellRequest) (*emptypb.Empty, error)
	// CompleteLoadSession завершает сессию загрузки
	CompleteLoadSession(context.Context, *CompleteLoadSessionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCourierServiceServer()
}

// UnimplementedCourierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourierServiceServer struct{}

func (UnimplementedCourierServiceServer) GetCells(context.Context, *GetCellsRequest) (*GetCellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCells not implemented")
}
func (UnimplementedCourierServiceServer) StartLoadSession(context.Context, *StartLoadSessionRequest) (*LoadSession, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLoadSession not implemented")
}
func (UnimplementedCourierServiceServer) LoadCell(context.Context, *LoadCellRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadCell not implemented")
}
func (UnimplementedCourierServiceServer) CompleteLoadSession(context.Context, *CompleteLoadSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteLoadSession not implemented")
}
func (UnimplementedCourierServiceServer) mustEmbedUnimplementedCourierServiceServer() {}
func (UnimplementedCourierServiceServer) testEmbeddedByValue()                        {}

// UnsafeCourierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourierServiceServer will
// result in compilation errors.
type UnsafeCourierServiceServer interface {
	mustEmbedUnimplementedCourierServiceServer()
}

func RegisterCourierServiceServer(s grpc.ServiceRegistrar, srv CourierServiceServer) {
	// If the following call panics, it indicates UnimplementedCourierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CourierService_ServiceDesc, srv)
}

func _CourierService_GetCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServiceServer).GetCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourierService_GetCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServiceServer).GetCells(ctx, req.(*GetCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierService_StartLoadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServiceServer).StartLoadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourierService_StartLoadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServiceServer).StartLoadSession(ctx, req.(*StartLoadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierService_LoadCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServiceServer).LoadCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourierService_LoadCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServiceServer).LoadCell(ctx, req.(*LoadCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierService_CompleteLoadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteLoadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServiceServer).CompleteLoadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourierService_CompleteLoadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServiceServer).CompleteLoadSession(ctx, req.(*CompleteLoadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CourierService_ServiceDesc is the grpc.ServiceDesc for CourierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.CourierService",
	HandlerType: (*CourierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCells",
			Handler:    _CourierService_GetCells_Handler,
		},
		{
			MethodName: "StartLoadSession",
			Handler:    _CourierService_StartLoadSession_Handler,
		},
		{
			MethodName: "LoadCell",
			Handler:    _CourierService_LoadCell_Handler,
		},
		{
			MethodName: "CompleteLoadSession",
			Handler:    _CourierService_CompleteLoadSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/v1/courier.proto",
}
